### PR TITLE
Add keyboard accessibility to move crop area with arrow keys

### PR DESCRIPTION
**Pull request by JGuardiola95**
This PR adds keyboard support for moving the crop area in react-easy-crop using the arrow keys, addressing issue #569.

- Users can now move the crop area using the arrow keys.
- The movement is based on a customizable step size (controlled via the keyboardStep prop).

<details>
  <summary>📦 Published PR as canary version: <code>5.1.0--canary.570.646b997.0</code></summary>
  <br />

  :sparkles: Test out this PR locally via:
  
  ```bash
  npm install react-easy-crop@5.1.0--canary.570.646b997.0
  # or 
  yarn add react-easy-crop@5.1.0--canary.570.646b997.0
  ```
</details>

### CODE REVIEW

**Comment by ValentinH** [comment]
Thanks for this PR, it looks good to me. Could you please reference the new option on the README?

**Comment by JGuardiola95** [comment]
> Thanks for this PR, it looks good to me. Could you please reference the new option on the README?

Done! 👍

**Review by ValentinH — APPROVED** [review]

**Comment by ValentinH** [comment]
Thank you for this contribution!

**Comment by ValentinH** [comment]
@allcontributors add @JGuardiola95 for code

**Pull request merged**
